export const SectionHeight = {
    userSelect: 'none',
    position: 'absolute',
    bottom: '-6px',
    height: '13px',
    background: '#eee',
    border: '1px solid #ccc',
    boxSizing: 'border-box',
    cursor: 'row-resize',
    fontSize: '11px',
    color: '#555',
    fontFamily: 'arial',
    padding: '0px 3px',
    zIndex: '1000',
    left: '0px',
    right: '0px',
    margin: '0px 50px',
    width: '45px',
    lineHeight: '10px'
};