export const CHOOSE_BOX = 'CHOOSE_BOX';
export const CHOOSE_SECTION = 'CHOOSE_SECTION';
export const DESELECT_ELEMENTS = 'DESELECT_ELEMENTS';

export const CLICK_TOP_MENU_ITEM = 'CLICK_TOP_MENU_ITEM';
export const CHANGE_ALIGN_MODE = 'CHANGE_ALIGN_MODE';

export const CHANGE_ELEMENT_PROPERTY_VALUE = 'CHANGE_ELEMENT_PROPERTY_VALUE';

export const DELETE_SECTION = 'DELETE_SECTION';
export const ADD_SECTION = 'ADD_SECTION';
export const DUPLICATE_SECTION = 'DUPLICATE_SECTION';
export const MOVE_UP_SECTION = 'MOVE_UP_SECTION';
export const MOVE_DOWN_SECTION = 'MOVE_DOWN_SECTION';

export const DELETE_BOX = 'DELETE_BOX';
export const ADD_BOX = 'ADD_BOX';
export const DUPLICATE_BOX = 'DUPLICATE_BOX';
export const MOVE_UP_BOX = 'MOVE_UP_BOX';
export const MOVE_DOWN_BOX = 'MOVE_DOWN_BOX';
export const ZINDEX_UP_BOX = 'ZINDEX_UP_BOX';
export const ZINDEX_DOWN_BOX = 'ZINDEX_DOWN_BOX';
export const ALIGN_BOXES = 'ALIGN_BOXES';
export const COPY_BOX = 'COPY_BOX';
export const CUT_BOX = 'CUT_BOX';
export const PASTE_BOX = 'PASTE_BOX';
export const CLEAR_STYLE = 'CLEAR_STYLE';


export const ENTER_BOX = 'ENTER_BOX';
export const EXIT_BOX = 'EXIT_BOX';
export const DESELECT_INNER = 'DESELECT_INNER';

export const SAVE_TO_HISTORY = 'SAVE_TO_HISTORY';

export const ADD_ELEMENTS_TO_BUFFER = 'ADD_ELEMENTS_TO_BUFFER';

export const SET_STATE_HOVER = 'SET_STATE_HOVER';
export const SET_STATE_ACTIVE = 'SET_STATE_ACTIVE';
export const UNSET_STATE_HOVER_ACTIVE = 'UNSET_STATE_HOVER_ACTIVE';

export const BUILDER_ZOOM_OUT = 'BUILDER_ZOOM_OUT';
export const BUILDER_ZOOM_IN = 'BUILDER_ZOOM_IN';
export const BUILDER_ZOOM_RESET = 'BUILDER_ZOOM_RESET';

export const LOAD_CURRENT_PAGE_TO_BUILDER = 'LOAD_CURRENT_PAGE_TO_BUILDER';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const PREVIEW_PAGE = 'PREVIEW_PAGE';

export const UPDATE_TEXT_VALUES = 'UPDATE_TEXT_VALUES';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const DELETE_START = 'DELETE_START';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';

export const SAVE_WEBSITE_DATA_FROM_SERVER = 'SAVE_WEBSITE_DATA_FROM_SERVER';
export const CREATE_WEBSITE = 'CREATE_WEBSITE';
export const LOAD_WEBSITE = 'LOAD_WEBSITE';
export const ACTION_START = 'ACTION_START';
export const ACTION_FAIL = 'ACTION_FAIL';
export const ADD_PAGE_SUCCESS = 'ADD_PAGE_SUCCESS';
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS';
export const ACTION_SUCCESS = 'ACTION_SUCCESS';
export const SAVE_PAGE_STRUCTURE_TO_STORE = 'SAVE_PAGE_STRUCTURE_TO_STORE';
export const SAVE_PAGE_IN_STATE = 'SAVE_PAGE_IN_STATE';